# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dubble_pb2 as dubble__pb2


class DubbleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.translateAndVoiceStream = channel.stream_stream(
                '/dubble.Dubble/translateAndVoiceStream',
                request_serializer=dubble__pb2.AudioData.SerializeToString,
                response_deserializer=dubble__pb2.AudioData.FromString,
                )


class DubbleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def translateAndVoiceStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DubbleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'translateAndVoiceStream': grpc.stream_stream_rpc_method_handler(
                    servicer.translateAndVoiceStream,
                    request_deserializer=dubble__pb2.AudioData.FromString,
                    response_serializer=dubble__pb2.AudioData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dubble.Dubble', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dubble(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def translateAndVoiceStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/dubble.Dubble/translateAndVoiceStream',
            dubble__pb2.AudioData.SerializeToString,
            dubble__pb2.AudioData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
