# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dubble.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64ubble.proto\x12\x06\x64ubble\"I\n\tAudioData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x05\x12\x0c\n\x04rate\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x05 \x01(\x05\x32M\n\x06\x44ubble\x12\x43\n\x17translateAndVoiceStream\x12\x11.dubble.AudioData\x1a\x11.dubble.AudioData(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dubble_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIODATA._serialized_start=24
  _AUDIODATA._serialized_end=97
  _DUBBLE._serialized_start=99
  _DUBBLE._serialized_end=176
# @@protoc_insertion_point(module_scope)
